apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
