sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%env(SENTRY_ENVIRONMENT)%'
        release: 'wager-service@%env(APP_VERSION)%'
        traces_sample_rate: '%env(float:SENTRY_TRACES_SAMPLE_RATE)%'
        profiles_sample_rate: 1.0
        send_default_pii: true
        attach_stacktrace: true
        capture_silenced_errors: true