{{- if .Values.components.argocd }}
# ArgoCD self-manage - takes over from bootstrap installation
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-96"
  labels:
    {{- include "layer-0.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}

  sources:
    # Values from git repo
    - repoURL: {{ .Values.gitRepo }}
      targetRevision: {{ .Values.gitRevision }}
      ref: values
    # ArgoCD Helm chart
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: {{ .Values.versions.argocd }}
      helm:
        valueFiles:
          - $values/shared/infrastructure/argocd/helm-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    {{- include "layer-0.syncPolicy" . | nindent 4 }}
{{- end }}
